name       : libmbim
version    : 1.16.2
release    : 7
source     :
    - https://freedesktop.org/software/libmbim/libmbim-1.16.2.tar.xz : eb494fee2c200daf4f5cc8a40061d24a3dfafe8c59151c95c6a826fd96dcb262
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : Library for talking to WWAN modems
description: |
    libmbim is a glib-based library for talking to WWAN modems and devices which speak the Mobile Interface Broadband Model (MBIM) protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
