name       : libmbim
version    : 1.16.0
release    : 6
source     :
    - https://www.freedesktop.org/software/libmbim/libmbim-1.16.0.tar.xz : c8ca50beeddd4b43309df5b698917268303bf176cea58fe4fe53d5bf0e93fac2
license    :
    - GPL-2.0
    - LGPL-2.1
component  : network.base
summary    : Library for talking to WWAN modems
description: |
    libmbim is a glib-based library for talking to WWAN modems and devices which speak the Mobile Interface Broadband Model (MBIM) protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
