name       : libmbim
version    : 1.26.0
release    : 11
source     :
    - https://www.freedesktop.org/software/libmbim/libmbim-1.26.0.tar.xz : 1e1f0926b22c77210442129eca689722ecf324ab9c9abf421a5c989f46e813cf
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : Library for talking to WWAN modems
description: |
    libmbim is a glib-based library for talking to WWAN modems and devices which speak the Mobile Interface Broadband Model (MBIM) protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
