name       : libmbim
version    : 1.14.0
release    : 4
source     :
    - http://www.freedesktop.org/software/libmbim/libmbim-1.14.0.tar.xz : ca8d52a95a18cbabae8f15f83f1572316e888b6504f946e6645d24405127ab5b
license    : LGPL-2.0
component  : network.base
summary    : Library for talking to WWAN modems
description: |
    libmbim is a glib-based library for talking to WWAN modems and devices which speak the Mobile Interface Broadband Model (MBIM) protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
