name       : libmbim
version    : 1.26.4
release    : 12
source     :
    - https://www.freedesktop.org/software/libmbim/libmbim-1.26.4.tar.xz : f688cec4c4586a17575f5e327448ce62f2000ef6a07c9e4589873d4a68568ad9
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : Library for talking to WWAN modems
description: |
    libmbim is a glib-based library for talking to WWAN modems and devices which speak the Mobile Interface Broadband Model (MBIM) protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
